POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 2",
    "description": "Category 2 description"
}

###

GET http://localhost:8080/category/3dacce45-3dd2-4ef1-bb50-776be02f46ee HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 3",
    "description": "Product 3 description",
    "price": 100,
    "category_id": "3dacce45-3dd2-4ef1-bb50-776be02f46ee",
    "image_url": "http://cdn.example.com"
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/d989953a-a52a-480e-9a70-9f103f10a999 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/category/3dacce45-3dd2-4ef1-bb50-776be02f46ee HTTP/1.1
Host: localhost:8080
Content-Type: application/json
